[build]
  command = ""
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Test için COEP'i kapatıyoruz (sonra tekrar açarız)
[[headers]]
  for = "/*"
  [headers.values]
    "Cross-Origin-Opener-Policy" = "same-origin"
    # "Cross-Origin-Embedder-Policy" = "require-corp"   ← bu satırı yorum satırı yap veya sil